[project]
name = "kids_messages"
version = "1.0.0"
description = "Sets the Kids Alert message on ProPresenter"
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"